export const ACCESS_TOKEN_SAVE = "ACCESS_TOKEN_SAVE";
export const ACCESS_TOKEN_SAVE_SUCCESS = "ACCESS_TOKEN_SAVE_SUCCESS";
export const ACCESS_TOKEN_SAVE_FAILURE = "ACCESS_TOKEN_SAVE_FAILURE";
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";