export const ACCESS_TOKEN_SAVE = "ACCESS_TOKEN_SAVE";
export const ACCESS_TOKEN_SAVE_SUCCESS = "ACCESS_TOKEN_SAVE_SUCCESS";
export const ACCESS_TOKEN_SAVE_FAILURE = "ACCESS_TOKEN_SAVE_FAILURE";
export const PHONE_AUTH = 'PHONE_AUTH';
export const PHONE_AUTH_VERIFY = 'PHONE_AUTH_VERIFY';
export const AUTH_SET_STATUS = "AUTH_SET_STATUS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";